name: Pylint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3.1.1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint-django
    - name: Analysing the ilo_web project
      run: |
        pylint --load-plugins pylint_django --django-settings-module=ilo_web.settings ilo_web
    - name: Analysing the ilo2 project
      run: |
        pylint --load-plugins pylint_django --django-settings-module=ilo_web.settings ilo2
